my_robot_description:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: 'left_wheel_joint'
    right_wheel: 'right_wheel_joint'
    publish_rate: 50.0               
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
 
    wheel_separation: 0.25
    wheel_radius: 0.1
 
    wheel_separation_multiplier: 1.0 
    wheel_radius_multiplier: 1.0 
 
    cmd_vel_timeout: 1.0
     
    base_frame_id: base_footprint
     
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.55 
        min_velocity: -0.55
        has_acceleration_limits: true
        max_acceleration: 0.25 
        min_acceleration: -0.25
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 0.3
        min_velocity: -0.3
        has_acceleration_limits: true
        max_acceleration: 0.3  
        min_acceleration: -0.3